export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DEL_INGREDIENT = 'DEL_INGREDIENT';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';

export const BEGIN_SEND_DATA = 'SEND_DATA';
export const SUCCESS_SEND_DATA = 'SUCCESS_SEND_DATA';
export const FAILURE_SEND_DATA = 'FAILURE_SEND_DATA';
export const BEGIN_FETCH_DATA = 'BEGIN_FETCH_DATA';
export const SUCCESS_FETCH_DATA = 'SUCCESS_FETCH_DATA';
export const FAILURE_FETCH_DATA = 'FAILURE_FETCH_DATA';

export const BEGIN_AUTH = 'BEGIN_AUTH';
export const SUCCESS_AUTH = 'SUCCESS_AUTH';
export const FAILURE_AUTH = 'FAILURE_AUTH';
export const LOGOUT = 'LOGOUT';